# Generated by Django 5.1.7 on 2025-04-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0002_zohoauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zohoauth',
            name='expires_in',
            field=models.IntegerField(),
        ),
    ]
