# Generated by Django 5.1.7 on 2025-04-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Leads', '0003_alter_zohoauth_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_source',
            field=models.CharField(choices=[('Website', 'Website'), ('Social Media', 'Social Media'), ('Referral', 'Referral'), ('Event', 'Event'), ('Other', 'Other')], default='website', max_length=100),
        ),
    ]
