# Generated by Django 5.1.7 on 2025-04-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMeeting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendlyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_start_time', models.DateTimeField()),
                ('invitee_name', models.CharField(max_length=255)),
                ('invitee_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='CalendlyUser',
        ),
    ]
