# Generated by Django 5.1.7 on 2025-04-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookMeeting', '0002_calendlyevent_delete_calendlyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendlyevent',
            name='calendly_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
